spring:
  application:
    name: user-service
  config:
    import: optional:file:./user-service/.env[.properties]
  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5                # Minimum number of idle connections in the pool
      maximum-pool-size: 20           # Maximum number of connections in the pool
      idle-timeout: 30000             # Max time an idle connection can stay in the pool (milliseconds)
      connection-timeout: 30000       # Max time to wait for a connection from the pool (milliseconds)
      max-lifetime: 1800000           # Max lifetime of a connection (milliseconds)
  jpa:
    hibernate:
      ddl-auto: update  # Adjust based on your needs (e.g., 'none', 'validate', 'update', 'create')
    show-sql: true       # Optional: Show SQL queries in logs for debugging
    properties:
      hibernate:
        format_sql: true # Format SQL for better readability in logs
        use_sql_comments: true # Include SQL comments in the logs (optional)

grpc:
  server:
    port: 9000